# ?? ??(properties)
#server.port=8081
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

# ?? ??(yaml)
server:
  port: 8081
spring:
  mvc:
    view:
      prefix: /WEB-INF/Views/
      suffix: .jsp

  application:
    name: monkey

  zipkin:
    base-url: http://localhost:9411